# Generated by Django 4.1.7 on 2023-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(choices=[('1', 'Dean'), ('2', 'Vice'), ('3', 'Head'), ('4', 'Dr'), ('4', 'TA')], max_length=255, unique=True),
        ),
    ]
