# Generated by Django 4.2 on 2023-04-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dean', 'Dean'), ('vice', 'Vice'), ('head', 'Head'), ('dr', 'Dr'), ('ta', 'TA')], max_length=4)),
                ('title', models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr'), ('Eng', 'TA')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='tasker/files/tasks')),
                ('status', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('receivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='tasker.staff')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.staff')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='tasker/files/responses')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.staff')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_response', to='tasker.task')),
            ],
        ),
    ]
