# Generated by Django 4.1.7 on 2023-03-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.staff'),
        ),
    ]
