# Generated by Django 4.2 on 2023-05-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_alter_taskresponse_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='staff',
            name='Department',
            field=models.CharField(choices=[('Computer_Science', 'CS'), ('Artificial_Intelligence', 'AI'), ('Information_System', 'IS'), ('Communication_Network', 'Network'), ('General', 'Gen')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Dean', 'Dean'), ('Vice_Dean', 'V.Dean'), ('Head_of_department', 'Head'), ('Doctor', 'Doctor'), ('Secretary', 'Sec'), ('Assistant', 'Assistant'), ('Admin', 'Admin')], max_length=40),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('Professor', 'Prof'), ('Associate_Professor', 'Associate.Prof'), ('Assistant_Professor', 'Assistant.Prof'), ('Instructor', 'Instructor'), ('General', 'General')], max_length=40),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(max_length=100)),
                ('sender_department', models.CharField(max_length=100)),
                ('sender_college', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ordinary', 'Ordinary'), ('casual', 'Casual'), ('sick', 'Sick'), ('unpaid', 'Unpaid')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by_dean', models.BooleanField(default=False)),
                ('accepted_by_vice_dean', models.BooleanField(default=False)),
                ('accepted_by_head_of_department', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_leaves', to='tasker.staff')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.staff')),
            ],
        ),
    ]
