# Generated by Django 4.1.7 on 2023-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_alter_task_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
