# Generated by Django 4.2 on 2023-05-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_alter_task_options_staff_department_alter_staff_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Casual', 'Casual'), ('Sick', 'Sick'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('receiver', models.CharField(max_length=50)),
                ('sender_role', models.CharField(max_length=20)),
                ('sender_department', models.CharField(max_length=50)),
                ('sender_college', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(None, 'Pending'), ('Accepted', 'Accepted'), ('Refused', 'Refused')], max_length=10, null=True)),
                ('approved_by', models.CharField(max_length=20, null=True)),
                ('dean_approved', models.BooleanField(default=False)),
                ('vice_dean_approved', models.BooleanField(default=False)),
                ('head_of_department_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
