# Generated by Django 4.1.7 on 2023-03-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_remove_staff_name_alter_staff_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr'), ('Eng', 'TA')], max_length=150),
        ),
    ]
