# Generated by Django 4.2 on 2023-05-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_leaverequest_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasker.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='dean_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='head_of_department_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='vice_dean_approved',
            field=models.BooleanField(null=True),
        ),
    ]
