# Generated by Django 4.1.7 on 2023-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_alter_staff_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('1', 'Dean'), ('2', 'Vice'), ('3', 'Head'), ('4', 'Dr'), ('4', 'TA')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
