# Generated by Django 4.1.7 on 2023-03-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresponse',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasker.staff'),
            preserve_default=False,
        ),
    ]
