# Generated by Django 4.1.7 on 2023-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_taskresponse_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('dean', 'Dean'), ('vice', 'Vice'), ('head', 'Head'), ('dr', 'Dr'), ('ta', 'TA')], max_length=4),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr'), ('Eng', 'TA')], max_length=4),
        ),
    ]
