# Generated by Django 4.2 on 2023-05-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_alter_leaverequest_sender_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='college',
            field=models.CharField(default='CSIS', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='sender_college',
            field=models.CharField(default='CSIS', max_length=50),
        ),
    ]
