# Generated by Django 4.1.7 on 2023-03-30 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0007_alter_staff_role_alter_staff_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresponse',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_response', to='tasker.task'),
        ),
    ]
