# Generated by Django 4.2 on 2023-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0007_staff_college_alter_leaverequest_sender_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='sender_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
