# Generated by Django 4.2 on 2023-05-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0008_leaverequest_sender_name_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='sender_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
