# Generated by Django 3.2.12 on 2023-04-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0009_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasker/images/tasks'),
        ),
    ]
