# Generated by Django 3.2.12 on 2023-04-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0010_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
