# Generated by Django 4.2 on 2023-04-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0012_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='العنوان',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
