# Generated by Django 4.2 on 2023-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0013_task_العنوان'),
    ]

    operations = [
        migrations.CreateModel(
            name='الوظيفة',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
