# Generated by Django 4.2 on 2023-04-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0014_الوظيفة'),
    ]

    operations = [
        migrations.DeleteModel(
            name='الوظيفة',
        ),
    ]
